name: news_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  provider: ^6.1.2
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Exo
      fonts:
        - asset: assets\fonts\Exo-Bold.ttf
        - asset: assets\fonts\EXO-Medium.ttf
        - asset: assets\fonts\EXO-Regular.ttf
        - asset: assets\fonts\EXO-Semibold.ttf
